//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long Id { get; set; }
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientBusinessName { get; set; }
        public string ClientLogoURL { get; set; }
        public string ClientEmailMain { get; set; }
        public string ClientEmailSales { get; set; }
        public string ClientEmailSupport { get; set; }
        public string ClientPhoneMain { get; set; }
        public string ClientPhoneSales { get; set; }
        public string ClientPhoneSupport { get; set; }
        public string ClientAddress { get; set; }
        public string ClientCity { get; set; }
        public string ClientPostal { get; set; }
        public string ClientWebsite { get; set; }
        public Nullable<int> AdminAccountLimit { get; set; }
        public Nullable<int> ManagerAccountLimit { get; set; }
        public Nullable<int> UserAccountLimit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ClientCRMLink { get; set; }
        public string Comment { get; set; }
        public string ClientPassword { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
