//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Ship_Country { get; set; }
        public string Ship_State { get; set; }
        public string Ship_City { get; set; }
        public Nullable<int> Ship_Pincode { get; set; }
        public string Bill_Country { get; set; }
        public string Bill_State { get; set; }
        public string Bill_City { get; set; }
        public Nullable<int> Bill_Pincode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
