//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long Id { get; set; }
        public Nullable<long> LeadId { get; set; }
        public string AgentId { get; set; }
        public string Email1 { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
