//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentReturn
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnStatus { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string Comment { get; set; }
        public string AdminId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> InvestmentId { get; set; }
        public string TransactionType { get; set; }
    
        public virtual Investment Investment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
