//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investment()
        {
            this.InvestmentReturns = new HashSet<InvestmentReturn>();
        }
    
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> InvestedAmount { get; set; }
        public Nullable<decimal> ReturnPercentage { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<System.DateTime> FirstPayDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string iStatus { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string iMode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentReturn> InvestmentReturns { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
