//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadFollowup
    {
        public long Id { get; set; }
        public Nullable<long> LeadId { get; set; }
        public string CallStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public string FollowupStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Lead Lead { get; set; }
    }
}
