//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.LeadFollowups = new HashSet<LeadFollowup>();
            this.Sales = new HashSet<Sale>();
            this.Emails = new HashSet<Email>();
            this.LeadForwardeds = new HashSet<LeadForwarded>();
        }
    
        public long Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string LeadSource { get; set; }
        public string LeadType { get; set; }
        public string LeadStatus { get; set; }
        public Nullable<System.DateTime> LeadCreationDate { get; set; }
        public string AssignedToUser { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<bool> DND { get; set; }
        public string Location { get; set; }
        public string PinCode { get; set; }
        public string AdminId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadFollowup> LeadFollowups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadForwarded> LeadForwardeds { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
