//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string Purpose { get; set; }
        public string Reason { get; set; }
        public string LeaveStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
