//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerHistory
    {
        public long Id { get; set; }
        public string TypeOfTransaction { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateofTransaction { get; set; }
        public string PurposeofTransaction { get; set; }
        public string AdminId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string TransactionDetails { get; set; }
        public string Status { get; set; }
        public Nullable<long> ReferenceId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
    }
}
