//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long Id { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> ProductSalePrice { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string TransactionDetails { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string Comment { get; set; }
        public string AdminId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string SaleByUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ProductsService ProductsService { get; set; }
    }
}
