//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> SpecialAllowance { get; set; }
        public Nullable<decimal> TravellingAllowance { get; set; }
        public Nullable<decimal> DistanceAllowance { get; set; }
        public Nullable<decimal> MobileInternetAllowance { get; set; }
        public Nullable<decimal> ExpensesPaid { get; set; }
        public Nullable<decimal> AdvanceSalary { get; set; }
        public Nullable<decimal> LoanDeduction { get; set; }
        public Nullable<decimal> ArrearCF { get; set; }
        public Nullable<decimal> ArrearBF { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> MealAllowance { get; set; }
        public Nullable<decimal> CabAllowance { get; set; }
        public Nullable<decimal> OtherAllowance { get; set; }
        public Nullable<decimal> OtherDeductions { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
