//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductsService()
        {
            this.Orders = new HashSet<Order>();
            this.Sales = new HashSet<Sale>();
        }
    
        public long Id { get; set; }
        public string ProductTitle { get; set; }
        public string ProductCode { get; set; }
        public string ProductImage { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public string Description { get; set; }
        public string Summary { get; set; }
        public string EmailBody { get; set; }
        public string EmailSubject { get; set; }
        public bool IsActive { get; set; }
        public string AdminId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
