//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long Id { get; set; }
        public Nullable<long> LeadId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public Nullable<System.DateTime> Practice1Date { get; set; }
        public string Practice1Status { get; set; }
        public Nullable<System.DateTime> Practice2Date { get; set; }
        public string Practice2Status { get; set; }
        public Nullable<System.DateTime> Practice3Date { get; set; }
        public string Practice3Status { get; set; }
        public Nullable<System.DateTime> Practice4Date { get; set; }
        public string Practice4Status { get; set; }
        public Nullable<System.DateTime> ProjectLiveDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual ProductsService ProductsService { get; set; }
    }
}
