//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallingCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string MobilePersonal { get; set; }
        public string MobileHome { get; set; }
        public string AddressLocal { get; set; }
        public string AddressPermanent { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> TotalExpYears { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> SalaryDate { get; set; }
        public string Skills { get; set; }
        public string Department { get; set; }
        public string EmployeeCode { get; set; }
        public string AdminId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
